version: '3.9'

services:
  tn.postgres:
    image: postgres:latest
    container_name: tn-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"