name: .NET
concurrency: dotnet-build

on:
  push:
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/dotnet-build.yml'
  workflow_dispatch:

jobs:
  build:
    name: üõ†Ô∏è Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        if: steps.cache-tests.outputs.cache-hit != 'true'
        with:
          dotnet-version: 7.0.x
      - name: Cache nuget packages
        uses: actions/cache@v3
        if: steps.cache-tests.outputs.cache-hit != 'true'
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/*.Packages.props', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore dependencies
        if: steps.cache-tests.outputs.cache-hit != 'true'
        run: dotnet restore Trusov.NET.sln
      - name: Build
        if: steps.cache-tests.outputs.cache-hit != 'true'
        run: dotnet build Trusov.NET.sln -c release --no-restore
  
  test:
    name: üßê Test
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Test
        run: dotnet test Trusov.NET.sln -c release --no-build --no-restore -l trx --results-directory ./allure-results
  
  compile-allure:
    name: üîÉ Compile allure pages
    runs-on: ubuntu-latest
    permissions: write-all
    needs: test
    
    steps:
      - name: Cache testing results
        id: cache-tests
        uses: actions/cache@v3
        with:
          path: ./allure-results
          key: ${{ needs.build.outputs.cache-key }}
      
      - name: Download history
        uses: actions/download-artifact@v3
        with:
          name: allure-history
          path: "${{ github.workspace }}/allure-history"
        continue-on-error: true

      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          subfolder: ${{ github.event.number }}
          keep_reports: 20

      - name: Store history
        uses: actions/upload-artifact@v3
        with:
          name: allure-history
          path: "${{ github.workspace }}/allure-history"

      - name: Upload GitHub Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: "${{ github.workspace }}/allure-history"

  deploy-pages:
    name: üöÄ Deploy test summary on github pages
    runs-on: ubuntu-latest
    permissions: write-all
    needs: compile-allure
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy Allure reports to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.1

      - name: Post allure test run link
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Link to allure test run:  
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}